<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    /* 
      promise对象的异常穿透 
        1.当使用promise的then链式调用时，可以再最后指定失败的回调
        2.前面任何操作出现了异常，都会传到最后失败的回到中处理
    */

    let p = new Promise((resolve,reject)=>{
      setTimeout(()=>{
        resolve('ok')
      },1000)
    })

    p.then(value=>{
      console.log(111)
      throw '我在这出错了'
    }).then(value=>{
      console.log(222)
    }).then(value=>{
      console.log(333)
    }).catch(reason=>{
      console.warn(reason)
    })

  </script>
</body>
</html>